
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lcfhbeyiaobtkojiuhqe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxjZmhiZXlpYW9idGtvaml1aHFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5MTc4MTYsImV4cCI6MjA2MjQ5MzgxNn0.7rnN_Z7X5SbDn-0qPB9xYysQWrHICHCbRjX4coTlT0g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
